# Generated by typst/repositories.bzl
load("@rules_typst//typst:toolchain.bzl", "typst_toolchain")

typst_toolchain(
    name = "typst_toolchain",
    target_tool = select({
      "@bazel_tools//src/conditions:host_windows": "typst-{platform}/typst.exe",
      "//conditions:default": "typst-{platform}/typst",
    })
)
